# Generated by Django 5.0.7 on 2024-07-16 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200, verbose_name='место привычки')),
                ('time', models.DateTimeField(verbose_name='время привычки')),
                ('action', models.CharField(max_length=200, verbose_name='действие')),
                ('is_pleasant', models.BooleanField(blank=True, null=True, verbose_name='приятная')),
                ('frequency_number', models.PositiveIntegerField()),
                ('frequency_unit', models.CharField(choices=[('minutes', 'минуты'), ('hours', 'часы'), ('days', 'дни')], default='days', max_length=10)),
                ('reward', models.CharField(blank=True, max_length=200, null=True, verbose_name='Вознаграждение')),
                ('duration', models.DurationField()),
                ('is_public', models.BooleanField()),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='создатель привычки')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
