# Generated by Django 5.0.7 on 2024-07-25 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='duration',
            field=models.DurationField(verbose_name='длительность действия'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency_number',
            field=models.PositiveIntegerField(verbose_name='количество раз'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency_unit',
            field=models.CharField(choices=[('minutes', 'минуты'), ('hours', 'часы'), ('days', 'дни')], default='days', max_length=10, verbose_name='единицы измерения'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='is_public',
            field=models.BooleanField(verbose_name='публичная'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='related_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='связанная привычка'),
        ),
    ]
